  const express = require("express");
  const router = express.Router();

  //Array of NIKKE characters with sprites
  const nikkeCharacters = [
    { id: 1, nama: "Rapi", gambar: "/sprites/rapi.png", role: "Attacker" , burstType: "Burst III", rarity: "SR" },
    { id: 2, nama: "Anis", gambar: "/sprites/anis.png", role: "Defender" , burstType: "Burst II", rarity: "SR" },
    { id: 3, nama: "Neon", gambar: "/sprites/neon.png", role: "Supporter" , burstType: "Burst I" , rarity: "SR"},
    { id: 4, nama: "Snow White", gambar: "/sprites/snowwhite.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR" },
    { id: 5, nama: "Modernia", gambar: "/sprites/modernia.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR"},
    { id: 6, nama: "Alice", gambar: "/sprites/alice.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR"},
    { id: 7, nama: "Liter", gambar: "/sprites/liter.png", role: "Supporter" , burstType: "Burst I" , rarity: "SSR"},
    { id: 8, nama: "Scarlet", gambar: "/sprites/scarlet.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR"},
    { id: 9, nama: "Helm", gambar: "/sprites/helm.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR"},
    { id: 10, nama: "Dolla", gambar: "/sprites/dolla.png", role: "Supporter" , burstType: "Burst II", rarity: "SSR" },
    { id: 11, nama: "Eunhwa", gambar: "/sprites/eunhwa.png", role: "Attacker" , burstType: "Burst II", rarity: "SSR" },
    { id: 12, nama: "Exia", gambar: "/sprites/exia.png", role: "Supporter" , burstType: "Burst I" , rarity: "SSR"},
    { id: 13, nama: "Ludmilla", gambar: "/sprites/ludmilla.png", role: "Defender" , burstType: "Burst I", rarity: "SSR" },
    { id: 14, nama: "Makima", gambar: "/sprites/makima.png", role: "Defender" , burstType: "Burst II", rarity: "SSR" },
    { id: 15, nama: "Mica", gambar: "/sprites/mica.png", role: "Supporter" , burstType: "Burst I", rarity: "SR" },
    { id: 16, nama: "Power", gambar: "/sprites/power.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR"},
    { id: 17, nama: "Yuni", gambar: "/sprites/yuni.png", role: "Defender" , burstType: "Burst II", rarity: "SSR" },
    { id: 18, nama: "Tove", gambar: "/sprites/tove.png", role: "Supporter" , burstType: "Burst I" , rarity: "SSR"},
    { id: 19, nama: "Viper", gambar: "/sprites/viper.png", role: "Attacker" , burstType: "Burst II", rarity: "SSR" },
    { id: 20, nama: "Trony", gambar: "/sprites/trony.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 21, nama: "Soda", gambar: "/sprites/soda.png", role: "Supporter" , burstType: "Burst I", rarity: "SSR" },
    { id: 22, nama: "Rupee", gambar: "/sprites/rupee.png", role: "Attacker" , burstType: "Burst II", rarity: "SSR" },
    { id: 23, nama: "Anne", gambar: "/sprites/n102.png", role: "Supporter" , burstType: "Burst I" , rarity: "SR"},
    { id: 24, nama: "EVE", gambar: "/sprites/eve.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 25, nama: "Mast", gambar: "/sprites/mast.png", role: "Supporter" , burstType: "Burst II", rarity: "SSR" },
    { id: 26, nama: "Emma", gambar: "/sprites/emma.png", role: "Supporter" , burstType: "Burst I" , rarity: "SSR"},
    { id: 27, nama: "Centi", gambar: "/sprites/centi.png", role: "Defender" , burstType: "Burst II" , rarity: "SSR"},
    { id: 28, nama: "Harran", gambar: "/sprites/harran.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 29, nama: "Rosanna", gambar: "/sprites/rosanna.png", role: "Attacker" , burstType: "Burst I" , rarity: "SSR"},
    { id: 30, nama: "Julia", gambar: "/sprites/julia.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 31, nama: "Bay", gambar: "/sprites/bay.png", role: "Attacker" , burstType: "Burst II" , rarity: "SSR"},
    { id: 32, nama: "Alice: Wonderland Bunny", gambar: "/sprites/BAlice.png", role: "Supporter" , burstType: "Burst I" , rarity: "SSR"},
    { id: 33, nama: "Anchor", gambar: "/sprites/anchor.png", role: "Defender" , burstType: "Burst I" , rarity: "SR"},
    { id: 34, nama: "Anchor: Innocent Maid", gambar: "/sprites/MAnchor.png", role: "Supporter" , burstType: "Burst II", rarity: "SSR" },
    { id: 35, nama: "Anis: Sparkling Summer", gambar: "/sprites/SAnis.png", role: "Supporter" , burstType: "Burst III" , rarity: "SSR"},
    { id: 36, nama: "Anne: Miracle Fairy", gambar: "/sprites/XAnne.png", role: "Supporter" , burstType: "Burst II" , rarity: "SSR"},
    { id: 37, nama: "Arcana", gambar: "/sprites/arcana.png", role: "Supporter" , burstType: "Burst II" , rarity: "SSR"},
    { id: 38, nama: "Aria", gambar: "/sprites/aria.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 39, nama: "Asuka Shikinami Langley", gambar: "/sprites/Asuka.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 40, nama: "Asuka: WILLE", gambar: "/sprites/WAsuka.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 41, nama: "Belorta", gambar: "/sprites/belorta.png", role: "Attacker" , burstType: "Burst II" , rarity: "SR"},
    { id: 42, nama: "Biscuit", gambar: "/sprites/biscuit.png", role: "Supporter" , burstType: "Burst II", rarity: "SSR" },
    { id: 43, nama: "Blanc", gambar: "/sprites/blanc.png", role: "Defender" , burstType: "Burst II", rarity: "SSR" },
    { id: 44, nama: "Bready", gambar: "/sprites/bready.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 45, nama: "Brid", gambar: "/sprites/brid.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR"},
    { id: 46, nama: "Cinderella", gambar: "/sprites/cinderella.png", role: "Defender" , burstType: "Burst III" , rarity: "SSR"},
    { id: 47, nama: "Clay", gambar: "/sprites/clay.png", role: "Supporter" , burstType: "Burst II" , rarity: "SSR"},
    { id: 48, nama: "Cocoa", gambar: "/sprites/cocoa.png", role: "Supporter" , burstType: "Burst I" , rarity: "SSR"},
    { id: 49, nama: "Crow", gambar: "/sprites/crow.png", role: "Defender" , burstType: "Burst III" , rarity: "SSR"},
    { id: 50, nama: "Crown", gambar: "/sprites/crown.png", role: "Defender" , burstType: "Burst II" , rarity: "SSR"},
    { id: 51, nama: "D", gambar: "/sprites/d.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 52, nama: "D: Killer Wife", gambar: "/sprites/DKW.png", role: "Supporter" , burstType: "Burst I"  , rarity: "SSR"},
    { id: 53, nama: "Delta", gambar: "/sprites/delta.png" , role: "Defender" , burstType: "Burst II", rarity: "SR"},
    { id: 54, nama: "Diesel", gambar: "/sprites/diesel.png" , role: "Defender" , burstType: "Burst II", rarity: "SSR"},
    { id: 55, nama: "Dorothy", gambar: "/sprites/dorothy.png", role: "Supporter" , burstType: "Burst III" , rarity: "SSR"},
    { id: 56, nama: "Dorothy: Serendipity", gambar: "/sprites/SDoro.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 57, nama: "Drake", gambar: "/sprites/drake.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 58, nama: "Ein", gambar: "/sprites/ein.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 59, nama: "Elegg", gambar: "/sprites/elegg.png", role: "Supporter" , burstType: "Burst II"  , rarity: "SSR" },
    { id: 60, nama: "Elegg: Boom and Shock", gambar: "/sprites/SElegg.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 61, nama: "Emilia", gambar: "/sprites/emilia.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 62, nama: "Epinel", gambar: "/sprites/epinel.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 63, nama: "Ether", gambar: "/sprites/ether.png", role: "Defender" , burstType: "Burst I" , rarity: "SR" },
    { id: 64, nama: "Eunhwa - Tactical Upgrade", gambar: "/sprites/eunhwa_tactical_upgrade.png" , role: "Attacker" , burstType: "Burst II", rarity: "SSR"},
    { id: 65, nama: "Emma - Tactical Upgrade", gambar: "/sprites/emma_tactical_upgrade.png", role: "Supporter" , burstType: "Burst I"   , rarity: "SSR"},
    { id: 66, nama: "Vesti - Tactical Upgrade", gambar: "/sprites/vesti_tactical_upgrade.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR"},
    { id: 67, nama: "Flora", gambar: "/sprites/flora.png" , role: "Supporter" , burstType: "Burst II" , rarity: "SSR"},
    { id: 68, nama: "Folkwang", gambar: "/sprites/folkwang.png", role: "Defender" , burstType: "Burst II" , rarity: "SSR"},
    { id: 69, nama: "Frima", gambar: "/sprites/frima.png", role: "Supporter" , burstType: "Burst I", rarity: "SSR"},
    { id: 70, nama: "Grave", gambar: "/sprites/grave.png", role: "Supporter" , burstType: "Burst II" , rarity: "SSR"},
    { id: 71, nama: "Guillotine", gambar: "/sprites/guillotine.png", role: "Supporter" , burstType: "Burst II"  , rarity: "SSR"},
    { id: 72, nama: "Guillotine - Winter Slayer", gambar: "/sprites/XGuillotine.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 73, nama: "Guilty", gambar: "/sprites/guilty.png" , role: "Attacker" , burstType: "Burst II", rarity: "SSR"},
    { id: 74, nama: "Himeno", gambar: "/sprites/himeno.png", role: "Supporter" , burstType: "Burst II" , rarity: "SR"},
    { id: 75, nama: "IDoll Flower", gambar: "/sprites/idoll_flower.png", role: "Defender" , burstType: "Burst I", rarity: "R" },
    { id: 76, nama: "IDoll Ocean", gambar: "/sprites/idoll_ocean.png", role: "Supporter" , burstType: "Burst I", rarity: "R" },
    { id: 77, nama: "IDoll Sun", gambar: "/sprites/idoll_sun.png", role: "Supporter" , burstType: "Burst III", rarity: "R" },
    { id: 78, nama: "Isabel", gambar: "/sprites/isabel.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR"},
    { id: 79, nama: "Jackal", gambar: "/sprites/jackal.png", role: "Defender" , burstType: "Burst I", rarity: "SSR" },
    { id: 80, nama: "Kilo", gambar: "/sprites/kilo.png" , role: "Defender" , burstType: "Burst III", rarity: "SSR"},
    { id: 81, nama: "Laplace", gambar: "/sprites/laplace.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 82, nama: "Leona", gambar: "/sprites/leona.png", role: "Supporter" , burstType: "Burst II"  , rarity: "SSR"},
    { id: 83, nama: "Lily", gambar: "/sprites/lily.png", role: "Supporter" , burstType: "Burst II" , rarity: "SR" },
    { id: 84, nama: "Little Mermaid", gambar: "/sprites/Siren1.png" , role: "Supporter" , burstType: "Burst I", rarity: "SSR" },
    { id: 86, nama: "Ludmilla - Winter Owner", gambar: "/sprites/XLudmilla.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 87, nama: "Maiden", gambar: "/sprites/maiden.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 88, nama: "Maiden - Ice Rose", gambar: "/sprites/XMaiden.png", role: "Defender" , burstType: "Burst III", rarity: "SSR" },
    { id: 89, nama: "Mari Makinami Illustrious", gambar: "/sprites/mari.png", role: "Supporter" , burstType: "Burst II" , rarity: "SSR" },
    { id: 90, nama: "Mary", gambar: "/sprites/mary.png" , role: "Supporter" , burstType: "Burst I" , rarity: "SSR"},
    { id: 91, nama: "Mary - Bay Goddess", gambar: "/sprites/SMary.png", role: "Supporter" , burstType: "Burst I" , rarity: "SSR" },
    { id: 92, nama: "Mast - Romantic Maid", gambar: "/sprites/MMast.png", role: "Supporter" , burstType: "Burst II" , rarity: "SSR" },
    { id: 93, nama: "Maxwell", gambar: "/sprites/maxwell.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR"},
    { id: 94, nama: "Mica - Snow Buddy", gambar: "/sprites/XMica.png", role: "Supporter" , burstType: "Burst I" , rarity: "SSR" },
    { id: 95, nama: "Mihara", gambar: "/sprites/mihara.png", role: "Attacker" , burstType: "Burst III" , rarity: "SR"},
    { id: 96, nama: "Milk", gambar: "/sprites/milk.png" , role: "Attacker" , burstType: "Burst I" , rarity: "SSR"},
    { id: 97, nama: "Miranda", gambar: "/sprites/miranda.png" , role: "Supporter" , burstType: "Burst I" , rarity: "SSR"},
    { id: 98, nama: "Misato Katsuragi", gambar: "/sprites/misato_katsuragi.png" , role: "Supporter" , burstType: "Burst I", rarity: "SR" },
    { id: 99, nama: "Moran", gambar: "/sprites/moran.png", role: "Defender" , burstType: "Burst I" , rarity: "SSR"},
    { id: 100, nama: "Mori", gambar: "/sprites/mori.png" , role: "Defender" , burstType: "Burst II", rarity: "SSR"},
    { id: 102, nama: "Naga", gambar: "/sprites/naga.png", role: "Supporter" , burstType: "Burst II" , rarity: "SSR" },
    { id: 103, nama: "Neon - Blue Ocean", gambar: "/sprites/SNeon.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 104, nama: "Nero", gambar: "/sprites/nero.png", role: "Defender" , burstType: "Burst II" , rarity: "SSR"},
    { id: 105, nama: "Neve", gambar: "/sprites/neve.png", role: "Attacker" , burstType: "Burst III" , rarity: "SR" },
    { id: 106, nama: "Nihilister", gambar: "/sprites/nihilister.png", role: "Attacker" , burstType: "Burst II" , rarity: "SSR" },
    { id: 107, nama: "Noah", gambar: "/sprites/noah.png" , role: "Defender" , burstType: "Burst III", rarity: "SSR"},
    { id: 108, nama: "Noir", gambar: "/sprites/noir.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR" },
    { id: 109, nama: "Noise", gambar: "/sprites/noise.png", role: "Supporter" , burstType: "Burst I" , rarity: "SSR" },
    { id: 110, nama: "Novel", gambar: "/sprites/novel.png" , role: "Defender" , burstType: "Burst II", rarity: "SSR"},
    { id: 111, nama: "Pascal", gambar: "/sprites/pascal.png" , role: "Supporter" , burstType: "Burst I", rarity: "SR" },
    { id: 112, nama: "Pepper", gambar: "/sprites/pepper.png", role: "Supporter" , burstType: "Burst I"  , rarity: "SSR"},
    { id: 113, nama: "Phantom", gambar: "/sprites/phantom.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 114, nama: "Poli", gambar: "/sprites/poli.png", role: "Defender" , burstType: "Burst II" , rarity: "SSR"},
    { id: 115, nama: "Privaty", gambar: "/sprites/privaty.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 116, nama: "Privaty - Unkind Maid", gambar: "/sprites/MPrivaty.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR"},
    { id: 117, nama: "Product 08", gambar: "/sprites/Product_08.png", role: "Supporter" , burstType: "Burst I" , rarity: "R" },
    { id: 118, nama: "Product 12", gambar: "/sprites/Product_12.png" , role: "Attacker" , burstType: "Burst III", rarity: "R" },
    { id: 119, nama: "Product 23", gambar: "/sprites/Product_23.png", role: "Supporter" , burstType: "Burst II", rarity: "R"  },
    { id: 120, nama: "Quency", gambar: "/sprites/quency.png" , role: "Supporter" , burstType: "Burst II" , rarity: "SSR"},
    { id: 121, nama: "Quency - Escape Queen", gambar: "/sprites/qeq.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 122, nama: "Quiry", gambar: "/sprites/quiry.png", role: "Supporter" , burstType: "Burst III"  , rarity: "SSR"},
    { id: 123, nama: "Ram", gambar: "/sprites/ram.png" , role: "Defender" , burstType: "Burst I", rarity: "SR"},
    { id: 124, nama: "Rapi - Red Hood", gambar: "/sprites/RRH.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 126, nama: "Rapunzel", gambar: "/sprites/rapunzel.png" , role: "Supporter" , burstType: "Burst I", rarity: "SSR"},
    { id: 127, nama: "Rapunzel - Pure Grace", gambar: "/sprites/rapunzel_pure_grace.png" , role: "Defender" , burstType: "Burst I", rarity: "SSR" },
    { id: 128, nama: "Red Hood", gambar: "/sprites/red_hood1.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 129, nama: "Rei", gambar: "/sprites/rei.png", role: "Defender" , burstType: "Burst I", rarity: "SSR"},
    { id: 130, nama: "Rei Ayanami", gambar: "/sprites/rei_ayanami.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 131, nama: "Rem", gambar: "/sprites/rem.png", role: "Supporter" , burstType: "Burst II" , rarity: "SSR" },
    { id: 132, nama: "Rosanna - Chic Ocean", gambar: "/sprites/SRosanna.png", role: "Supporter" , burstType: "Burst II" , rarity: "SSR" },
    { id: 133, nama: "Rouge", gambar: "/sprites/rouge.png", role: "Supporter" , burstType: "Burst I" , rarity: "SSR" },
    { id: 134, nama: "Rumani", gambar: "/sprites/rumani.png", role: "Defender" , burstType: "Burst I", rarity: "SSR" },
    { id: 135, nama: "Rupee - Winter Shopper", gambar: "/sprites/XRupee.png", role: "Defender" , burstType: "Burst I", rarity: "SSR"  },
    { id: 136, nama: "Sakura", gambar: "/sprites/sakura.png", role: "Supporter" , burstType: "Burst I", rarity: "SSR"  },
    { id: 137, nama: "Sakura - Bloom in Summer", gambar: "/sprites/SSakura.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 138, nama: "Scarlet - Black Shadow", gambar: "/sprites/scarlet_black_shadow.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 139, nama: "Signal", gambar: "/sprites/signal.png", role: "Attacker" , burstType: "Burst II" , rarity: "SSR"},
    { id: 140, nama: "Sin", gambar: "/sprites/sin.png", role: "Defender" , burstType: "Burst II" , rarity: "SSR" },
    { id: 141, nama: "Snow White - Innocent Days", gambar: "/sprites/snow_white_innocent_days.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 142, nama: "Soda - Twinkling Bunny", gambar: "/sprites/BSoda.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR"},
    { id: 143, nama: "Soldier EG", gambar: "/sprites/soldier_eg.png" , role: "Attacker" , burstType: "Burst III", rarity: "R"},
    { id: 144, nama: "Sora", gambar: "/sprites/sora.png" , role: "Supporter" , burstType: "Burst I" , rarity: "SSR"},
    { id: 145, nama: "Soldier FA", gambar: "/sprites/soldier_fa.png", role: "Defender" , burstType: "Burst II", rarity: "R" },
    { id: 146, nama: "Soldier OW", gambar: "/sprites/soldier_ow.png", role: "Supporter" , burstType: "Burst I"  , rarity: "R"},
    { id: 147, nama: "Soline", gambar: "/sprites/soline.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 148, nama: "Sugar", gambar: "/sprites/sugar.png", role: "Attacker" , burstType: "Burst III" , rarity: "SSR"},
    { id: 149, nama: "Tia", gambar: "/sprites/tia.png", role: "Defender" , burstType: "Burst I" , rarity: "SSR"},
    { id: 150, nama: "Rei Ayanami (Tentative Name)", gambar: "sprites/Rei_Ayanami_(Tentative_Name).png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 151, nama: "Trina", gambar: "/sprites/trina.png", role: "Supporter" , burstType: "Burst II" , rarity: "SSR" },
    { id: 152, nama: "Trony", gambar: "/sprites/trony.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 153, nama: "Vesti", gambar: "/sprites/vesti.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 156, nama: "Volume", gambar: "/sprites/volume.png", role: "Supporter" , burstType: "Burst I" , rarity: "SSR" },
    { id: 157, nama: "Yan", gambar: "/sprites/yan.png", role: "Supporter" , burstType: "Burst I" , rarity: "SSR" },
    { id: 158, nama: "Yulha", gambar: "/sprites/yulha.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 160, nama: "Zwei", gambar: "/sprites/zwei.png", role: "Supporter" , burstType: "Burst I", rarity: "SSR"  },
    { id: 161, nama: "2B", gambar: "/sprites/2b.png" , role: "Attacker" , burstType: "Burst III", rarity: "SSR"},
    { id: 162, nama: "A2", gambar: "/sprites/a2.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 163, nama: "Ade", gambar: "/sprites/ade.png", role: "Supporter" , burstType: "Burst II", rarity: "SSR"  },
    { id: 164, nama: "Admi", gambar: "/sprites/admi.png", role: "Supporter" , burstType: "Burst II", rarity: "SSR"  },
    { id: 165, nama: "Sakura Suzuhara", gambar: "/sprites/sakura_suzuhara.png", role: "Supporter" , burstType: "Burst I" , rarity: "SR" },
    { id: 166, nama: "Mihara - Bonding Chain", gambar: "/sprites/mihara_bonding_chain.png", role: "Attacker" , burstType: "Burst III", rarity: "SSR" },
    { id: 167, nama: "Helm - Aquamarine", gambar: "/sprites/SHelm.png", role: "Attacker" , burstType: "Burst II", rarity: "SSR" },
  ];

  // Route to display sorted NIKKE characters
  // ✅ Gunakan router.get untuk menangani permintaan GET ke path "/"
  router.get("/", (req, res) => {
    // Sort berdasarkan nama alfabet
    nikkeCharacters.sort((a, b) => a.nama.localeCompare(b.nama));

    res.render("todo-array", {
      layout: "layouts/main-layout",
      characters: nikkeCharacters
    });
  });

  // ✅ Export langsung router, bukan { router }
  module.exports = router;